serverAddr = "us.gaianet.network"
serverPort = 7000
metadatas.deviceId = "device-4448d99364b73bbf28130570"

[[proxies]]
name = "0x115ce49e4a9a2f1bfbe8fd2022cfe3ac831c0cf2.us.gaianet.network"
type = "http"
localPort = 8080
#remotePort = 80
subdomain = "0x115ce49e4a9a2f1bfbe8fd2022cfe3ac831c0cf2"
